import Client from '../models/Client.js';
import Blog from '../models/Blog.js';

// -------------------------------- client  --------------------------------
// @desc    Add a new client
// @route   POST /api/clients
// @access  Private (Admin)
// ---------------------- add client function ----------------------
export const addClient = async (req, res) => {
  try {
    const { name, websiteLink } = req.body;
    // Check if image was uploaded
    if (!req.file) {
      return res.status(400).json({ success: false, error: 'Please upload a client logo' });
    }

    // req.file.path contains the secure URL generated by Cloudinary
    const logoUrl = req.file.path;
    // Replace the undefined block with this:
    if (!logoUrl){
      return res.status(400).json({ success: false, error: "Image upload failed" });
    }
    if(!websiteLink) {
    // Save to database
    const newClient = await Client.create({ name, logoUrl });

    res.status(201).json({ success: true, data: newClient });
    }
    else {
    // Save to database
    const newClient = await Client.create({ name, logoUrl, websiteLink });

    res.status(201).json({ success: true, data: newClient });}

  } catch (error) {
    console.error("Error creating client:", error);
    res.status(500).json({ success: false, error: 'Server Error while creating client' });
  }
};

export const deleteClient = async (req, res) => {
  try {
    const { id } = req.params;
    if (!id) {
      return res.status(400).json({ success: false, error: 'no client found' });
    }

    // === FIX: Pass just the 'id' string, not an object ===
    await Client.findByIdAndDelete(id); 
    
    res.status(200).json({ success: true, message: "Client deleted successfully" });
  } catch (error) {
    console.error("Error deleting clients:", error);
    res.status(500).json({ success: false, error: 'Server Error while deleting clients' });
  }
};

export const editClient = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, websiteLink } = req.body;

    if (!id || !name) {
      return res.status(400).json({ success: false, error: "Client id and name are required" });
    }

    const updateData = { name };

    if (websiteLink) updateData.websiteLink = websiteLink;
    if (req.file) updateData.logoUrl = req.file.path;

    const updatedClient = await Client.findByIdAndUpdate(id, updateData, { new: true });

    if (!updatedClient) {
      return res.status(404).json({ success: false, error: "Client not found" });
    }

    res.status(200).json({ success: true, data: updatedClient, clientstatus: "updated" });
  } catch (error) {
    console.error("Error update clients:", error);
    res.status(500).json({ success: false, error: "Server Error while updating clients" });
  }
};

// -------------------------------- blogs  --------------------------------

// @desc    Create a new blog"
// @route   POST /api/blogs
// ---------------------- create blog function ----------------------
export const createBlog = async (req, res) => {
  try {
    const { title, content } = req.body;
    
    if (!req.file) {
      return res.status(400).json({ success: false, error: 'Please upload a featured image' });
    }
    
    const newBlog = await Blog.create({ title, content, imageUrl: req.file.path });

    res.status(201).json({ success: true, data: newBlog });
  } catch (error) {
    console.error("Error creating blog:", error);
    res.status(500).json({ success: false, error: 'Server Error' });
  }
};

export const deleteblog = async (req, res) => {
  try {
    const { id } = req.params;
    if (!id) {
      return res.status(400).json({ success: false, error: 'no blog found' });
    }

    // === FIX: Pass just the 'id' string, not an object ===
    await Blog.findByIdAndDelete(id); 
    
    res.status(200).json({ success: true, message: "Blog deleted successfully" });
  } catch (error) {
    console.error("Error deleting blogs:", error);
    res.status(500).json({ success: false, error: 'Server Error while deleting blog' });
  }
};

export const editBlog = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, content } = req.body;

    if (!id || !title || !content) {
      return res.status(400).json({ success: false, error: "Blog id, title and content are required" });
    }

    const updateData = { title, content };

    if (req.file) updateData.imageUrl = req.file.path;

    const updatedBlog = await Blog.findByIdAndUpdate(id, updateData, { new: true });

    if (!updatedBlog) {
      return res.status(404).json({ success: false, error: "Blog not found" });
    }

    res.status(200).json({ success: true, data: updatedBlog, clientstatus: "updated" });
  } catch (error) {
    console.error("Error update blogs:", error);
    res.status(500).json({ success: false, error: "Server Error while updating blogs" });
  }
};